defaults:
  # Job
  n_steps: 500_000
  run_name: none
  resume_id:
  input_dir: ./data/train
  eval_dir: ./data/eval
  log_interval: 200
  save_interval: 200
  eval_interval: 2000
  data_workers: 6  # need 6 to not bottleneck on unzipping npz, 4 is not enough
  enable_profiler: True
  verbose: False

  # Env
  image_key: image
  image_size: 7
  image_channels: 4
  image_categorical: True
  map_key: map
  map_size: 11
  map_channels: 4
  map_categorical: True
  action_dim: 7

  # Training
  iwae_samples: 1
  image_weight: 1.0
  adam_lr: 3.0e-4
  adam_lr_ac: 1.0e-4
  adam_eps: 1.0e-5
  keep_state: True
  batch_length: 50
  batch_size: 50
  device: "cuda:0"
  grad_clip: 200
  image_decoder_min_prob: 0
  amp: True

  # Eval
  test_batches: 61  # For unbiased test needs to be enough to cover full episodes
  test_batch_size: 10  # Smaller for faster test
  eval_batches: 61  # Big enough to reach episode end (xN). +1 to log last episode
  eval_samples: 10  # Big enough for good sampling
  eval_batch_size: 10  # Limited by GPU mem

  # Model
  model: world
  embed_dim: 1024
  embed_rnn: none
  deter_dim: 2048
  stoch_dim: 32
  hidden_dim: 256
  gru_layers: 1
  gru_type: gru
  image_encoder: dense
  image_encoder_layers: 3
  image_decoder: dense
  image_decoder_layers: 2
  reward_decoder_layers: 3
  terminal_decoder_layers: 3
  map_stoch_dim: 64
  map_model: direct
  map_decoder: dense
  map_hidden_layers: 4
  map_hidden_dim: 1024
  mem_model: none
  mem_loss_type:
  global_dim: 0

  # Actor Critic
  discount: 0.999
  actor_ent: 0.001
  target_interval: 100
  imag_horizon: 15
  # discount_lambda: 0.95

  # Generator
  generator_run: False
  generator_prefill_steps: 100000
  env_id:
  env_max_steps: 1500

minigrid:
  # Data
  input_dir: /data/MiniGrid-MazeS11N-v0_100M/episodes/
  eval_dir: /data/MiniGrid-MazeS11N-v0_100M/eval/

  # Env
  image_key: image
  image_size: 7
  image_channels: 4
  image_categorical: True
  map_key: map
  map_size: 11
  map_channels: 4
  map_categorical: True
  action_dim: 7

  # Model
  image_encoder: dense
  image_encoder_layers: 3
  image_decoder: dense
  image_decoder_layers: 2
  embed_dim: 256

minigrid_top: # Top-down observations instead of agent-centric
  # Data
  input_dir: /data/MiniGrid-MazeS11N-v0_100M/episodes/
  eval_dir: /data/MiniGrid-MazeS11N-v0_100M/eval/

  # Env
  image_key: map_masked
  image_size: 11
  image_channels: 8
  image_categorical: True
  map_key: map
  map_size: 11
  map_channels: 8
  map_categorical: True
  action_dim: 7

  # Model
  image_encoder: dense
  image_encoder_layers: 3
  image_decoder: dense
  image_decoder_layers: 2
  embed_dim: 256

miniworld:
  # Data
  input_dir: /data/MiniWorld-MazeS5GridN-v0_100M/train/
  eval_dir: /data/MiniWorld-MazeS5GridN-v0_100M/eval/

  # Env
  image_key: image
  image_size: 64
  image_channels: 3
  image_categorical: False
  map_key: map
  map_size: 9
  map_channels: 4
  map_categorical: True
  action_dim: 3

  # Model
  image_encoder: cnn
  image_decoder: cnn
  embed_dim: 1024

atari:
  # Generator
  env_id: Atari-Pong
  generator_run: True
  generator_prefill_steps: 100_000

  # Env
  image_key: image
  image_size: 64
  image_channels: 3
  image_categorical: False
  map_key:
  action_dim: 18

  # Model
  image_encoder: cnn
  image_decoder: cnn
  embed_dim: 1024
  map_model: none
