defaults:
  # Job
  n_steps: 100_000
  run_name: none
  resume_id:
  input_dir: ./data/train
  eval_dir: ./data/eval
  log_interval: 500
  save_interval: 5000
  eval_interval: 5000

  # Env
  channels: 4
  image_key: image
  map_key: map_centered
  map_size: 19

  # Training
  data_seq: True
  keep_state: True
  batch_length: 50
  batch_size: 50
  device: "cuda:0"

  # Eval
  eval_batches: 20  # For unbiased eval needs to be enough to cover full episodes
  eval_samples: 100
  full_eval_batches: 1
  full_eval_samples: 100
  full_eval_length: 500
  full_eval_size: 100

  # Model
  embed_dim: 256
  deter_dim: 200
  stoch_dim: 30
  hidden_dim: 200
  image_decoder: dense
  map_stoch_dim: 30
  map_model: direct
  mem_model: none
  mem_loss_type:
  global_dim: 0

  # Optimizer
  grad_clip: 100

  # Generator
  generator_run: False
  generator_env:
  generator_wait: 300
  generator_buffer: 0