defaults:
  run_name: none
  input_dir: ./data
  eval_dir: ./data_eval
  log_interval: 500
  save_path: ./log/model.pt
  save_interval: 10_000
  eval_interval: 10_000

  # Env
  channels: 4
  image_key: image
  map_key: map
  map_size: 7

  # Data
  data_seq: True
  keep_state: False

  # Training
  n_steps: 100_000
  batch_length: 15
  batch_size: 15
  device: 'cuda:0'

  # Eval
  full_eval_samples: 50

  # Model
  embed_dim: 256
  deter_dim: 200
  stoch_dim: 10
  hidden_dim: 200
  image_decoder: cnn

  # Optimizer
  grad_clip:
