dmlabapplesmall:
  n_steps: 500_000
  generator_workers: 10
  env_id: DmLab-explore_object_locations_small
  reward_decoder_categorical: [-10., -1., 0., 1., 2., 10.]
  reward_weight: 10.0

dmlabgoalsmall:
  n_steps: 500_000
  generator_workers: 10
  env_id: DmLab-explore_goal_locations_small
  reward_decoder_categorical: [-10., -1., 0., 1., 2., 10.]
  reward_weight: 10.0

dmlabteleport:
  n_steps: 500_000
  generator_workers: 10
  env_id: DmLab-rooms_select_nonmatching_object
  reward_decoder_categorical: [-10., -1., 0., 1., 2., 10.]
  reward_weight: 10.0

dmlabtmaze_online:
  env_id: DmLab-rooms_select_nonmatching_object

debug:
  env_id: DmLab-rooms_select_nonmatching_object
  generator_prefill_steps: 2_000
  device: cpu
  log_interval: 2
  save_interval: 10
  data_workers: 0
  generator_workers: 1
  batch_length: 15
  batch_size: 5
  imag_horizon: 1