shuffle:
  data_seq: False

offline_minigrid:
  input_dir: ./data/MiniGrid-Maze-v0/20210309_1541
  grad_clip: 100

adhoc:
  input_dir: ./data/MiniGrid-Maze-v0/20210309_1541
  run_name: adhoc
  device: cpu
  log_interval: 10
  image_decoder: 'cnn'