dmlabgoalsmall_kl3:
  n_steps: 1_000_000
  generator_workers: 10
  env_id: DmLab-explore_goal_locations_small
  reward_decoder_categorical: [-10., -1., 0., 1., 10.]
  kl_weight: 3.0
  reward_weight: 10.0

dmlabgoalsmall_kl10:
  n_steps: 1_000_000
  generator_workers: 10
  env_id: DmLab-explore_goal_locations_small
  reward_decoder_categorical: [-10., -1., 0., 1., 10.]
  kl_weight: 3.0
  reward_weight: 10.0

dmlabgoalsmall_kl3_d3072:
  n_steps: 1_000_000
  generator_workers: 10
  env_id: DmLab-explore_goal_locations_small
  reward_decoder_categorical: [-10., -1., 0., 1., 10.]
  kl_weight: 3.0
  reward_weight: 10.0
  deter_dim: 3072

dmlabtmaze_online_notbtt:
  env_id: DmLab-rooms_select_nonmatching_object
  keep_state: False

dmlabtmaze_online:
  env_id: DmLab-rooms_select_nonmatching_object

debug:
  env_id: DmLab-rooms_select_nonmatching_object
  generator_prefill_steps: 2_000
  device: cpu
  log_interval: 2
  save_interval: 10
  data_workers: 0
  generator_workers: 1
  batch_length: 15
  batch_size: 5
  imag_horizon: 1