# Atari

atari_pong:
  env_id: Atari-Pong
atari_breakout:
  env_id: Atari-Breakout
atari_montezuma:
  env_id: Atari-Montezuma_Revenge

# Miniworld

maze3d_apples:
  env_id: MiniWorld-MazeS7GridA4C-v0

# DMLab online

dmlab_rooms_select_nonmatching_object:
  env_id: DmLab-rooms_select_nonmatching_object
