densedec:
  image_decoder: dense

sequential:
  data_seq: True

shuffle:
  data_seq: False

offline_minigrid:
  n_steps: 100_000
  input_dir: ./data/MiniGrid-Maze-v0/20210309_1541
  grad_clip: 100

adhoc:
  n_steps: 10_000
  input_dir: ./data/MiniGrid-Maze-v0/20210309_1541
  run_name: adhoc
  device: cpu
  log_interval: 10
  image_decoder: cnn