# DMLab online

dmlabapplesmall:
  env_id: DmLab-explore_object_locations_small

dmlabgoalsmall:
  env_id: DmLab-explore_goal_locations_small

dmlabteleport:
  env_id: DmLab-rooms_select_nonmatching_object

# DMLab offline

dmlabteleport_off:
  env_id: DmLab-rooms_select_nonmatching_object
  offline_data_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_rooms_select_nonmatching_object/train
  offline_test_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_rooms_select_nonmatching_object/eval
  imag_horizon: 5

dmlabobjectfew_off:
  env_id: DmLab-explore_object_rewards_few
  offline_data_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_explore_object_rewards_few/train
  offline_test_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_explore_object_rewards_few/eval
  imag_horizon: 5

dmlabobjectmany_off:
  env_id: DmLab-explore_object_rewards_many
  offline_data_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_explore_object_rewards_many/train
  offline_test_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_explore_object_rewards_many/eval
  imag_horizon: 5

dmlabwatermaze_off:
  env_id: DmLab-rooms_watermaze
  offline_data_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_rooms_watermaze/train
  offline_test_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_rooms_watermaze/eval
  imag_horizon: 5
