# DMLab online

dmlabapplesmall:
  env_id: DmLab-explore_object_locations_small

dmlabgoalsmall:
  env_id: DmLab-explore_goal_locations_small

dmlabteleport:
  env_id: DmLab-rooms_select_nonmatching_object

dmlab_psychlab_arbitrary_vm:
  env_id: DmLab-psychlab_arbitrary_visuomotor_mapping

dmlab_rooms_collect_good_objects:
  env_id: DmLab-rooms_collect_good_objects_train
  env_id_eval: DmLab-rooms_collect_good_objects_test

dmlab_rooms_exploit_deferred_effects:
  env_id: DmLab-rooms_exploit_deferred_effects_train
  env_id_eval: DmLab-rooms_exploit_deferred_effects_test

# DMLab offline

dmlabteleport_off:
  env_id: DmLab-rooms_select_nonmatching_object
  offline_data_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_rooms_select_nonmatching_object/train
  offline_test_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_rooms_select_nonmatching_object/eval

dmlabobjectfew_off:
  env_id: DmLab-explore_object_rewards_few
  offline_data_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_explore_object_rewards_few/train
  offline_test_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_explore_object_rewards_few/eval

dmlabobjectmany_off:
  env_id: DmLab-explore_object_rewards_many
  offline_data_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_explore_object_rewards_many/train
  offline_test_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_explore_object_rewards_many/eval

dmlabwatermaze_off:
  env_id: DmLab-rooms_watermaze
  offline_data_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_rooms_watermaze/train
  offline_test_dir: gs://xcloud_public_bucket/danijar/memory_world_models/offline/rlu_dmlab_rooms_watermaze/eval
